"""empty message

Revision ID: 9b46e2a7df2b
Revises:
Create Date: 2017-06-13 08:24:39.867605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b46e2a7df2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable= False),
        sa.Column('first_name', sa.String(length= 128), nullable= False),
        sa.Column('last_name', sa.String(length= 128), nullable= False),
        sa.Column('email', sa.String(length= 128), nullable= False),
        sa.Column('password', sa.String(length= 255), nullable= False),
        sa.Column('admin', sa.Boolean(), nullable= False),
        sa.Column('created_at', sa.DateTime(), nullable= False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
    )

    op.create_table('confirmation_code',
        sa.Column('id', sa.Integer(), nullable= False),
        sa.Column('user_id', sa.Integer(), nullable= False),
        sa.Column('code', sa.String(length= 255), nullable= False),
        sa.Column('activated', sa.Boolean(), nullable= False, defalut= False),
        sa.Column('created_at', sa.DateTime(), nullable= False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('confirmation_code')
    op.drop_table('user')
    # ### end Alembic commands ###
